apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: codebasebranches.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: CodebaseBranch
    listKind: CodebaseBranchList
    plural: codebasebranches
    singular: codebasebranch
    shortNames:
      - cb
  scope: Namespaced
  version: v1alpha1