global:
  edpName: ""
  platform: "openshift"
name: reconciler
database:
  required: false
  host: edp-install-wizard-db
  name: edp-install-wizard-db
  port: 5432
image:
  name: reconciler
  version: latest