{{- if eq .Values.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: Role for reconciler-edp service account
    openshift.io/reconcile-protect: "false"
  name: {{ .Values.name }}-role-{{ .Values.namespace }}
rules:
  - apiGroups:
      - '*'
    attributeRestrictions: null
    resources:
      - securitycontextconstraints
    verbs:
      - patch
      - update
      - delete
      - get
      - list
      - create
  - apiGroups:
      - '*'
    attributeRestrictions: null
    resources:
      - gitservers
      - gitservers/status
      - gitservers/finalizers
      - codebases
      - codebases/status
      - codebases/finalizers
      - codebasebranches
      - codebasebranches/status
      - codebasebranches/finalizers
      - codebaseimagestreams
      - codebaseimagestreams/status
      - codebaseimagestreams/finalizers
      - gerrits
      - gerrits/finalizers
      - gerrits/status
      - gerritreplicationconfigs
      - gerritreplicationconfigs/status
      - jenkins
      - jenkins/finalizers
      - jenkins/status
      - jenkinses
      - jenkinses/finalizers
      - jenkinses/status
      - jenkinsserviceaccounts
      - jenkinsserviceaccounts/finalizers
      - jenkinsserviceaccounts/status
      - keycloaks
      - keycloaks/status
      - keycloakclients
      - keycloakclients/finalizers
      - keycloakclients/status
      - keycloakrealms
      - keycloakrealms/status
      - jenkinsserviceaccounts
      - jenkinsscripts
      - edpcomponents
    verbs:
      - '*'
  {{ end }}
